//https://newsapi.org/v2/top-headlines/sources?apiKey=0f7a5f9303f0486dbdd4c80ec54c9753
import 'dart:convert';
import 'dart:math';
import 'package:http/http.dart';

class NewsFatch {
  static Newsfatch() async {
    final _random = new Random();
    List sourcesId = [
      "abc-news",
      "al-jazeera-english",
      "associated-press",
      "bild",
      "bleacher-report",
      "bloomberg",
      "breitbart-news",
      "buzzfeed",
      "business-insider",
      "business-insider-uk",
      "cbc-news",
      "cbs-news",
      "channel-news-asia",
      "cnn",
      "cnn-es",
      "der-tagesspiegel",
      "die-zeit",
      "el-mundo",
      "engadget",
      "entertainment-weekly",
      "espn",
      "espn-cric-info",
      "financial-post",
      "financial-times",
      "fortune",
      "fox-news",
      "fox-sports",
      "globo",
      "google-news",
      "google-news-in",
      "guardian-uk",
      "hacker-news",
      "ign",
      "independent",
      "les-echos",
      "medical-news-today",
      "msnbc",
      "mtv-news",
      "national-geographic",
      "news24",
      "new-scientist",
      "new-york-magazine",
      "next-big-future",
      "newsweek",
      "npr",
      "politico",
      "recode",
      "rediff",
      "reuters",
      "techcrunch",
      "techradar",
      "thedailybeast",
      "the-economist",
      "the-globe-and-mail",
      "the-hindu",
      "the-hill",
      "the-irish-times",
      "the-jerusalem-post",
      "the-lad-bible",
      "the-new-york-times",
      "the-next-web",
      "the-sport-bible",
      "the-telegraph",
      "the-verge",
      "the-wall-street-journal",
      "the-washington-post",
      "the-washington-times",
      "time",
      "usa-today",
      "vice-news",
      "wired",
      "ynet",
      "abc-news-au",
      "business-insider-de",
      "cbc-news",
      "crypto-news",
      "daily-mail",
      "daily-mirror",
      "daily-telegraph-au",
      "der-spiegel",
      "economic-times",
      "el-pais",
      "espn-fc",
      "evening-standard",
      "global-times",
      "i-news",
      "inews",
      "india-today",
      "kicking-world",
      "le-monde",
      "metro",
      "news-com-au",
      "nz-herald",
      "nsw-news",
      "the-straits-times",
      "tokyo-np",
      "tokyo-sports",
      "tokyo-express",
      "times-of-india",
      "usatoday-sports",
      "washington-examiner",
      "yahoo-news",
      "yahoo-sports",
      "yahoo-finance",
      "the-huffington-post",
      "mirror-sport",
      "guardian-au",
      "guardian-de",
      "guardian-us",
      "guardian-in",
      "guardian-za",
      "guardian-ca",
      "guardian-au",
      "guardian-kr",
      "guardian-jp",
      "guardian-ru",
      "the-guardian-science",
      "guangming-daily",
    ];
    var sourcesID = sourcesId[_random.nextInt(sourcesId.length)];
    print(sourcesID);
    Response response = await get(
      Uri.parse(
        "https://newsapi.org/v2/top-headlines?sources=$sourcesID&apiKey=0f7a5f9303f0486dbdd4c80ec54c9753",
      ),
    );

    Map body_data = jsonDecode(response.body);
    List articles = body_data["articles"];
    //print(articles);
    print("**********************");

    final Newrandom = new Random();
    var myArticle = articles[_random.nextInt(articles.length)];
    print(myArticle);
  }
}
